default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
bird-ui-light: styles/bird-ui-light.scss
bird-ui-dark: styles/bird-ui-dark.scss
theme-ui-dark: styles/theme-ui-dark.scss
theme-ui-light: styles/theme-ui-light.scss
